import React, { useState, useEffect } from "react";
import { 
  StyleSheet, 
  Text, 
  View, 
  TouchableOpacity, 
  ActivityIndicator, 
  Alert, 
  ScrollView,
  SafeAreaView,
  TextInput,
  Modal,
  FlatList,
  Switch
} from "react-native";
import { useRouter } from "expo-router";
import * as SecureStore from "expo-secure-store";
import { 
  Truck as TruckIcon, 
  ShieldAlert as ShieldAlertIcon, 
  LogOut as LogOutIcon, 
  CreditCard as CreditCardIcon, 
  Activity as ActivityIcon, 
  Users as UsersIcon, 
  Settings as SettingsIcon,
  User as UserIcon,
  Check as CheckIcon,
  Bell as BellIcon,
  RefreshCw as RefreshCwIcon,
  FileText as FileTextIcon,
  X as XIcon,
  Lock as LockIcon,
  BookOpen as BookOpenIcon
} from "lucide-react-native";

const Truck = TruckIcon as any;
const ShieldAlert = ShieldAlertIcon as any;
const LogOut = LogOutIcon as any;
const CreditCard = CreditCardIcon as any;
const Activity = ActivityIcon as any;
const User = UserIcon as any;
const Check = CheckIcon as any;
const Bell = BellIcon as any;
const RefreshCw = RefreshCwIcon as any;
const FileText = FileTextIcon as any;
const X = XIcon as any;
const Lock = LockIcon as any;
const BookOpen = BookOpenIcon as any;
const Users = UsersIcon as any;
const Settings = SettingsIcon as any;

import { API_BASE_URL } from "../../constants/config";
import { useGPSBackground } from "../../hooks/useGPSBackground";
import * as ExpoLocation from "expo-location";

interface Student {
  id: number;
  name: string;
  school: string;
  status: "absent" | "awaiting" | "boarded" | "completed";
}

interface Payment {
  id: number;
  student_name?: string;
  student_id: number;
  month: string;
  amount_due: string;
  status: string;
  receipt_ref?: string;
  receipt_url?: string;
}

interface JourneyHistory {
  id: number;
  route_name: string;
  started_at: string;
  completed_at: string | null;
  status: string;
}

export default function DriverDashboard() {
  const router = useRouter();
  const { startTracking, stopTracking } = useGPSBackground();
  
  // Navigation Tabs state
  const [activeTab, setActiveTab] = useState<"home" | "payments" | "notifications" | "profile">("home");

  // Core Driver session states
  const [driverName, setDriverName] = useState("Driver");
  const [driverEmail, setDriverEmail] = useState("");
  const [driverId, setDriverId] = useState<number | null>(null);
  const [realDriverId, setRealDriverId] = useState<number | null>(null);
  const [assignedRouteId, setAssignedRouteId] = useState<number | null>(null);
  const [token, setToken] = useState("");
  const [isActive, setIsActive] = useState(false);
  const [activeJourneyId, setActiveJourneyId] = useState<number | null>(null);
  
  // Tab 1: Home Dashboard states
  const [students, setStudents] = useState<Student[]>([]);
  const [isLoadingStudents, setIsLoadingStudents] = useState(false);
  const [isSimulating, setIsSimulating] = useState(false);
  const [simCoords, setSimCoords] = useState<{ latitude: number; longitude: number } | null>(null);
  const [announcementMsg, setAnnouncementMsg] = useState("");
  const [isBroadcasting, setIsBroadcasting] = useState(false);

  // Tab 2: Payments states
  const [payments, setPayments] = useState<Payment[]>([]);
  const [isLoadingPayments, setIsLoadingPayments] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedPayment, setSelectedPayment] = useState<Payment | null>(null);
  const [rejectReason, setRejectReason] = useState("");
  const [isSubmittingVerification, setIsSubmittingVerification] = useState(false);

  // Tab 3: Notifications (Past Journeys) states
  const [journeyHistory, setJourneyHistory] = useState<JourneyHistory[]>([]);
  const [isLoadingHistory, setIsLoadingHistory] = useState(false);

  // Tab 4: Profile / Settings states
  const [profileSubView, setProfileSubView] = useState<"view" | "edit" | "settings">("view");
  const [driverPhone, setDriverPhone] = useState("");
  
  // UI settings state togglers
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [isNotificationsEnabled, setIsNotificationsEnabled] = useState(true);
  const [trackingFrequency, setTrackingFrequency] = useState("high");

  // Payment Config Settings
  const [paymentMode, setPaymentMode] = useState<"fixed" | "distance_based" | "hybrid">("fixed");
  const [fixedAmount, setFixedAmount] = useState("0");
  const [baseCharge, setBaseCharge] = useState("0");
  const [chargePerKm, setChargePerKm] = useState("0");
  const [dueDateDay, setDueDateDay] = useState("5");
  const [autoGenerateDay, setAutoGenerateDay] = useState("");
  const [isLoadingPaymentSettings, setIsLoadingPaymentSettings] = useState(false);
  // Password change
  const [oldPassword, setOldPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [isSubmittingPassword, setIsSubmittingPassword] = useState(false);
  // Onboarding status
  const [onboardingCompleted, setOnboardingCompleted] = useState(true);
  const [onboardingStep, setOnboardingStep] = useState(1);
  const [licenseNumber, setLicenseNumber] = useState("");
  const [vehicleNumber, setVehicleNumber] = useState("");
  const [vehicleType, setVehicleType] = useState("van");
  const [vehicleCapacity, setVehicleCapacity] = useState("12");
  const [routeName, setRouteName] = useState("");
  const [totalPassengers, setTotalPassengers] = useState(0);
  const [isOnboardingSubmitting, setIsOnboardingSubmitting] = useState(false);

  const themeColors = {
    background: isDarkMode ? "#000000" : "#F5F7FA",
    cardBg: isDarkMode ? "rgba(22, 22, 26, 0.85)" : "rgba(255, 255, 255, 0.85)",
    textPrimary: isDarkMode ? "#FFFFFF" : "#1C1C1E",
    textSecondary: isDarkMode ? "#8E8E93" : "#6E6E73",
    border: isDarkMode ? "rgba(255, 255, 255, 0.1)" : "rgba(0, 0, 0, 0.06)",
    inputBg: isDarkMode ? "rgba(30, 30, 35, 0.8)" : "rgba(242, 242, 247, 0.8)",
    headerBg: isDarkMode ? "rgba(10, 10, 12, 0.9)" : "rgba(255, 255, 255, 0.9)"
  };

  const themedStyles = {
    ...globalStyles,
    container: StyleSheet.flatten([globalStyles.container, { backgroundColor: themeColors.background }]),
    header: StyleSheet.flatten([globalStyles.header, { backgroundColor: themeColors.headerBg, borderColor: themeColors.border }]),
    card: StyleSheet.flatten([globalStyles.card, { backgroundColor: themeColors.cardBg, borderColor: themeColors.border }]),
    consoleCard: StyleSheet.flatten([globalStyles.consoleCard, { backgroundColor: themeColors.cardBg, borderColor: themeColors.border }]),
    sosCard: StyleSheet.flatten([globalStyles.sosCard, { backgroundColor: themeColors.cardBg, borderColor: themeColors.border }]),
    paymentCard: StyleSheet.flatten([globalStyles.paymentCard, { backgroundColor: themeColors.cardBg, borderColor: themeColors.border }]),
    textInput: StyleSheet.flatten([globalStyles.textInput, { backgroundColor: themeColors.inputBg, color: themeColors.textPrimary, borderColor: themeColors.border }]),
    welcome: StyleSheet.flatten([globalStyles.welcome, { color: themeColors.textSecondary }]),
    name: StyleSheet.flatten([globalStyles.name, { color: themeColors.textPrimary }]),
    sectionTitle: StyleSheet.flatten([globalStyles.sectionTitle, { color: themeColors.textPrimary }]),
    tabBar: StyleSheet.flatten([globalStyles.tabBar, { backgroundColor: themeColors.headerBg, borderColor: themeColors.border }])
  };

  const styles = themedStyles;

  // Initialize and load auth credentials
  useEffect(() => {
    async function initDashboard() {
      try {
        const sessionStr = await SecureStore.getItemAsync("school-van-auth-session");
        if (!sessionStr) {
          router.replace("/login");
          return;
        }

        const session = JSON.parse(sessionStr);
        setToken(session.token);
        setDriverName(session.user?.name || "Driver");
        setDriverEmail(session.user?.email || "");
        setDriverId(session.user?.id);
        setDriverPhone(session.user?.phone || "");

        const savedDarkMode = await SecureStore.getItemAsync("ui-dark-mode");
        if (savedDarkMode) setIsDarkMode(savedDarkMode === "true");

        // Fetch onboarding details to populate view fields
        try {
          const obRes = await fetch(`${API_BASE_URL}/driver/onboarding/status`, {
            headers: { Authorization: `Bearer ${session.token}` }
          });
          const obData = await obRes.json();
          if (obRes.ok) {
            if (obData.driverId) {
              setRealDriverId(obData.driverId);
            }
            if (obData.completed) {
              setLicenseNumber(obData.licenseNumber || "");
              setVehicleNumber(obData.vehicleDetails?.registrationNumber || "");
              setVehicleType(obData.vehicleDetails?.type || "van");
              setVehicleCapacity(String(obData.vehicleDetails?.capacity || "12"));
              setRouteName(obData.routeName || "");
              setOnboardingCompleted(true);
            } else {
              setOnboardingCompleted(false);
            }
          }
        } catch {}

        // Fetch driver record ID mappings
        const profileRes = await fetch(`${API_BASE_URL}/auth/me`, {
          headers: { Authorization: `Bearer ${session.token}` },
        });
        const profile = await profileRes.json();
        if (profileRes.ok && profile.driverId) {
          setRealDriverId(profile.driverId);
          // Check active status
          if (profile.activeJourneyId) {
            setIsActive(true);
            setActiveJourneyId(profile.activeJourneyId);
            loadJourneyStudents(profile.activeJourneyId);
          }
          // Fetch route mappings
          const routesRes = await fetch(`${API_BASE_URL}/routes?driver_id=${profile.driverId}`, {
            headers: { Authorization: `Bearer ${session.token}` }
          });
          const routesData = await routesRes.json().catch(() => []);
          if (routesRes.ok && routesData.length > 0) {
            setAssignedRouteId(routesData[0].id);
            setRouteName(routesData[0].route_name || "");
            setTotalPassengers(routesData[0].passenger_count || 0);
          }
        }
      } catch (err) {
        console.error("Dashboard init sync error:", err);
      }
    }
    initDashboard();
  }, []);

  // Watch/Load states on tab switches
  useEffect(() => {
    if (token) {
      if (activeTab === "payments") {
        loadPayments();
      } else if (activeTab === "notifications") {
        loadJourneyHistory();
      } else if (activeTab === "profile") {
        loadPaymentSettings();
        checkOnboardingStatus();
      }
    }
  }, [activeTab, token]);

  // GPS Simulation Loop
  useEffect(() => {
    let interval: any = null;
    if (isActive && isSimulating && activeJourneyId && token && simCoords) {
      let currentLat = simCoords.latitude;
      let currentLng = simCoords.longitude;

      interval = setInterval(async () => {
        currentLat += 0.00015;
        currentLng += 0.00015;

        try {
          const res = await fetch(`${API_BASE_URL}/tracking/location`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${token}`
            },
            body: JSON.stringify({ journeyId: activeJourneyId, lat: currentLat, lng: currentLng }),
          });
          if (!res.ok) {
            console.error("Simulator API push failure:", await res.text());
          }
        } catch (e) {
          console.error("Simulator broadcast connection error:", e);
        }
      }, 10000); // 10s intervals
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isActive, isSimulating, activeJourneyId, token, simCoords]);

  // ONBOARDING CHECKS
  const checkOnboardingStatus = async () => {
    try {
      const res = await fetch(`${API_BASE_URL}/driver/onboarding/status`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json();
      if (res.ok) {
        setOnboardingCompleted(data.completed);
        setOnboardingStep(data.step || 1);
      }
    } catch (e) {
      console.error(e);
    }
  };

  const handleOnboardingSubmit = async () => {
    if (!licenseNumber || !vehicleNumber || !routeName) {
      Alert.alert("Error", "Please fill in all onboarding fields");
      return;
    }
    setIsOnboardingSubmitting(true);
    try {
      const res = await fetch(`${API_BASE_URL}/driver/onboarding/submit`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          licenseNumber,
          vehicleDetails: {
            registrationNumber: vehicleNumber,
            type: vehicleType,
            seatCount: Number(vehicleCapacity),
            isAc: true
          },
          routeStops: [
            { name: routeName + " Start", order: 1, lat: 6.9271, lng: 79.8612 },
            { name: routeName + " End", order: 2, lat: 6.9371, lng: 79.8712 }
          ]
        })
      });
      if (res.ok) {
        Alert.alert("Success", "Onboarding completed successfully!");
        checkOnboardingStatus();
      } else {
        const err = await res.json();
        Alert.alert("Error", err.error || "Failed to submit onboarding");
      }
    } catch (e: any) {
      Alert.alert("Error", e.message || "Failed onboarding request");
    } finally {
      setIsOnboardingSubmitting(false);
    }
  };

  // LOAD JOURNEY ASSIGNED PASSENGERS
  const loadJourneyStudents = async (journeyId: number) => {
    setIsLoadingStudents(true);
    try {
      const res = await fetch(`${API_BASE_URL}/driver/journey/${journeyId}/students`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json().catch(() => []);
      if (res.ok) {
        setStudents(data);
      }
    } catch (err) {
      console.error("Load students error:", err);
    } finally {
      setIsLoadingStudents(false);
    }
  };

  // MANAGE BOARDING & DROPOFF
  const handleBoardStudent = async (studentId: number) => {
    if (!activeJourneyId) return;
    setIsLoadingStudents(true);
    try {
      const res = await fetch(`${API_BASE_URL}/driver/journey/${activeJourneyId}/board/${studentId}`, {
        method: "POST",
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.ok) {
        setStudents(prev => prev.map(s => s.id === studentId ? { ...s, status: "boarded" } : s));
      } else {
        const data = await res.json();
        Alert.alert("Boarding Failed", data.error || "Checkin request blocked by database.");
      }
    } catch (err: any) {
      Alert.alert("API Sync Failed", err.message || "Request blocked.");
    } finally {
      setIsLoadingStudents(false);
    }
  };

  const handleDropStudent = async (studentId: number) => {
    if (!activeJourneyId) return;
    setIsLoadingStudents(true);
    try {
      const res = await fetch(`${API_BASE_URL}/driver/journey/${activeJourneyId}/drop/${studentId}`, {
        method: "POST",
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.ok) {
        setStudents(prev => prev.map(s => s.id === studentId ? { ...s, status: "completed" } : s));
      } else {
        const data = await res.json();
        Alert.alert("Dropoff Failed", data.error || "Checkout request blocked by database.");
      }
    } catch (err: any) {
      Alert.alert("API Sync Failed", err.message || "Request blocked.");
    } finally {
      setIsLoadingStudents(false);
    }
  };

  // START & FINISH JOURNEY TRIP
  const handleToggleJourney = async () => {
    if (isActive) {
      Alert.alert("Complete Trip", "Confirm you have safely completed this route. This will finalize logs.", [
        { text: "Cancel", style: "cancel" },
        {
          text: "End Journey",
          onPress: async () => {
            try {
              const res = await fetch(`${API_BASE_URL}/driver/journey/${activeJourneyId}/complete`, {
                method: "POST",
                headers: { Authorization: `Bearer ${token}` },
              });
              if (res.ok) {
                await stopTracking();
                setIsActive(false);
                setIsSimulating(false);
                setActiveJourneyId(null);
                setStudents([]);
                Alert.alert("Route Completed", "Active logs saved to history logs.");
              }
            } catch (err) {
              Alert.alert("Failed", "Trip complete update blocked.");
            }
          }
        }
      ]);
    } else {
      Alert.alert("Start Journey", "This will activate live GPS tracking telemetry coordinates for parents.", [
        { text: "Cancel", style: "cancel" },
        {
          text: "Start Trip",
          onPress: async () => {
            try {
              const routeIdToUse = assignedRouteId || 1;
              const res = await fetch(`${API_BASE_URL}/driver/journey/start`, {
                method: "POST",
                headers: { 
                  "Content-Type": "application/json",
                  Authorization: `Bearer ${token}` 
                },
                body: JSON.stringify({ 
                  driver_id: realDriverId || driverId, 
                  route_id: routeIdToUse 
                }),
              });
              const data = await res.json();
              if (res.ok && data.journeyId) {
                setActiveJourneyId(data.journeyId);
                setIsActive(true);
                await startTracking(data.journeyId);
                loadJourneyStudents(data.journeyId);
              } else {
                Alert.alert("Error", data.error || "Unable to start journey route.");
              }
            } catch (err) {
              Alert.alert("Start Failed", "Connection error.");
            }
          }
        }
      ]);
    }
  };

  // SOS ALERTS BROADCAST
  const handleSOS = () => {
    Alert.alert("🚨 EMERGENCY SOS BROADCAST", "Are you sure you want to trigger an SOS alert? This will immediately notify parents with sound warnings.", [
      { text: "Cancel", style: "cancel" },
      {
        text: "Broadcast SOS",
        style: "destructive",
        onPress: async () => {
          try {
            const res = await fetch(`${API_BASE_URL}/driver/sos`, {
              method: "POST",
              headers: { 
                "Content-Type": "application/json",
                Authorization: `Bearer ${token}` 
              },
              body: JSON.stringify({ activeJourneyId })
            });
            if (res.ok) {
              Alert.alert("SOS Dispatched", "SOS flags activated. Parents have been notified.");
            }
          } catch {
            Alert.alert("SOS dispatch failure", "Signal connection failure.");
          }
        }
      }
    ]);
  };

  // ANNOUNCEMENTS BROADCASTER (POST /api/driver/announce)
  const handleBroadcastAnnouncement = async () => {
    if (!announcementMsg.trim()) {
      Alert.alert("Error", "Please input an announcement message");
      return;
    }
    setIsBroadcasting(true);
    try {
      const res = await fetch(`${API_BASE_URL}/driver/announce`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({ driver_id: realDriverId || driverId, message: announcementMsg.trim() }),
      });
      const data = await res.json();
      if (res.ok) {
        Alert.alert("Success", "Announcement broadcasted successfully!");
        setAnnouncementMsg("");
      } else {
        Alert.alert("Broadcast Failed", data.error || "Unable to broadcast message.");
      }
    } catch (e: any) {
      Alert.alert("Error", e.message || "Failed broadcasting message");
    } finally {
      setIsBroadcasting(false);
    }
  };

  // SIMULATOR TRIGGER
  const handleToggleSimulator = async () => {
    if (isSimulating) {
      setIsSimulating(false);
      setSimCoords(null);
    } else {
      try {
        const { status } = await ExpoLocation.requestForegroundPermissionsAsync();
        if (status !== "granted") {
          Alert.alert("Access Denied", "GPS access required for coordinate startup.");
          return;
        }
        const location = await ExpoLocation.getCurrentPositionAsync({ accuracy: ExpoLocation.Accuracy.Balanced });
        setSimCoords({
          latitude: location.coords.latitude,
          longitude: location.coords.longitude
        });
        setIsSimulating(true);
        Alert.alert("Simulator Active", "Mock vehicle coordinates starting from your actual position.");
      } catch (err) {
        Alert.alert("GPS Error", "Failed to retrieve coordinates.");
      }
    }
  };

  // TABS FETCHES (TAB 2: PAYMENTS)
  const loadPayments = async () => {
    setIsLoadingPayments(true);
    try {
      const res = await fetch(`${API_BASE_URL}/payments/driver/students`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json().catch(() => []);
      if (res.ok) setPayments(data);
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoadingPayments(false);
    }
  };

  const handleCalculateDues = async () => {
    Alert.alert("Generate Dues", "Confirm recalculating and generating payment statements for all assigned students?", [
      { text: "Cancel", style: "cancel" },
      {
        text: "Generate",
        onPress: async () => {
          setIsGenerating(true);
          try {
            const res = await fetch(`${API_BASE_URL}/payments/driver/generate`, {
              method: "POST",
              headers: { Authorization: `Bearer ${token}` },
            });
            if (res.ok) {
              Alert.alert("Success", "Dues statements calculations processed successfully!");
              loadPayments();
            } else {
              const data = await res.json();
              throw new Error(data.error);
            }
          } catch (err: any) {
            Alert.alert("Failed", err.message || "Recalculation failed.");
          } finally {
            setIsGenerating(false);
          }
        }
      }
    ]);
  };

  const handleVerifyReceipt = async (status: "paid" | "rejected") => {
    if (!selectedPayment) return;
    if (status === "rejected" && !rejectReason.trim()) {
      Alert.alert("Error", "Please input a rejection reason");
      return;
    }
    setIsSubmittingVerification(true);
    try {
      const res = await fetch(`${API_BASE_URL}/payments/driver/verify/${selectedPayment.id}`, {
        method: "PUT",
        headers: { 
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}` 
        },
        body: JSON.stringify({ status, reject_reason: rejectReason }),
      });
      if (res.ok) {
        Alert.alert("Success", `Receipt status marked: ${status}`);
        setSelectedPayment(null);
        setRejectReason("");
        loadPayments();
      }
    } catch {
      Alert.alert("API Error", "Sync failed.");
    } finally {
      setIsSubmittingVerification(false);
    }
  };

  // TAB 3: HISTORY JOURNEY LOGS
  const loadJourneyHistory = async () => {
    setIsLoadingHistory(true);
    try {
      const res = await fetch(`${API_BASE_URL}/driver/journey/history`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json().catch(() => []);
      if (res.ok) setJourneyHistory(data);
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoadingHistory(false);
    }
  };

  // TAB 4: SETTINGS & PRICING
  const loadPaymentSettings = async () => {
    setIsLoadingPaymentSettings(true);
    try {
      const res = await fetch(`${API_BASE_URL}/payments/driver/settings`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json();
      if (res.ok && data) {
        setPaymentMode(data.mode || "fixed");
        setFixedAmount(String(data.fixed_amount || 0));
        setBaseCharge(String(data.base_charge || 0));
        setChargePerKm(String(data.charge_per_km || 0));
        setDueDateDay(String(data.due_date_day || 5));
        setAutoGenerateDay(data.auto_generate_day ? String(data.auto_generate_day) : "");
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoadingPaymentSettings(false);
    }
  };

  const handleUpdatePaymentSettings = async () => {
    setIsLoadingPaymentSettings(true);
    try {
      const res = await fetch(`${API_BASE_URL}/payments/driver/settings`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          mode: paymentMode,
          fixed_amount: Number(fixedAmount),
          base_charge: Number(baseCharge),
          charge_per_km: Number(chargePerKm),
          due_date_day: Number(dueDateDay),
          auto_generate_day: autoGenerateDay.trim() ? Number(autoGenerateDay) : null
        })
      });
      if (res.ok) {
        Alert.alert("Success", "Fee pricing configuration updated successfully!");
      } else {
        const data = await res.json();
        Alert.alert("Failed", data.error || "Update rejected.");
      }
    } catch (e: any) {
      Alert.alert("Error", e.message || "Failed request.");
    } finally {
      setIsLoadingPaymentSettings(false);
    }
  };

  // PROFILE UPDATE / LOGOUT
  const handleUpdatePassword = async () => {
    if (!oldPassword || !newPassword) {
      Alert.alert("Error", "Please input password details");
      return;
    }
    setIsSubmittingPassword(true);
    // Mimics context session update locally as in the webapp:
    setTimeout(() => {
      Alert.alert("Success", "Password updated successfully!");
      setOldPassword("");
      setNewPassword("");
      setIsSubmittingPassword(false);
    }, 1000);
  };

  const handleSaveDriverProfile = async () => {
    try {
      const res = await fetch(`${API_BASE_URL}/driver/onboarding/submit`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          licenseNumber,
          vehicleDetails: {
            registrationNumber: vehicleNumber,
            type: vehicleType,
            capacity: Number(vehicleCapacity)
          },
          routeName
        })
      });
      if (res.ok) {
        Alert.alert("Success", "Driver profile details updated!");
        setProfileSubView("view");
      } else {
        const data = await res.json();
        Alert.alert("Error", data.error || "Failed to update profile.");
      }
    } catch {
      Alert.alert("Error", "Failed network request.");
    }
  };

  const handleDeleteAccount = async () => {
    Alert.alert(
      "Confirm Delete",
      "Are you absolutely sure you want to permanently delete your account? This action is irreversible.",
      [
        { text: "Cancel", style: "cancel" },
        { 
          text: "Delete Account", 
          style: "destructive",
          onPress: async () => {
            try {
              const res = await fetch(`${API_BASE_URL}/auth/me`, {
                method: "DELETE",
                headers: { Authorization: `Bearer ${token}` }
              });
              if (res.ok) {
                Alert.alert("Deleted", "Your account has been successfully deleted.");
                handleLogout();
              } else {
                Alert.alert("Error", "Failed to delete account from server.");
              }
            } catch (err) {
              Alert.alert("Error", "Network connection failure.");
            }
          }
        }
      ]
    );
  };

  const handleToggleDarkMode = async (value: boolean) => {
    setIsDarkMode(value);
    await SecureStore.setItemAsync("ui-dark-mode", value ? "true" : "false");
  };

  const handleLogout = async () => {
    await stopTracking();
    await SecureStore.deleteItemAsync("school-van-auth-session");
    await SecureStore.deleteItemAsync("school-van-active-journey-id");
    router.replace("/login");
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "paid": return { text: "#047857", bg: "#D1FAE5" };
      case "receipt_submitted": return { text: "#1D4ED8", bg: "#DBEAFE" };
      case "rejected": return { text: "#B91C1C", bg: "#FEE2E2" };
      case "overdue": return { text: "#C2410C", bg: "#FFEDD5" };
      default: return { text: "#B45309", bg: "#FEF3C7" };
    }
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: themeColors.background }]}>
      {/* 1. Header Area */}
      <View style={[styles.header, { backgroundColor: themeColors.headerBg, borderColor: themeColors.border }]}>
        <View>
          <Text style={[styles.welcome, { color: themeColors.textSecondary }]}>Driver Dashboard</Text>
          <Text style={[styles.name, { color: themeColors.textPrimary }]}>{driverName}</Text>
        </View>
        <TouchableOpacity style={styles.logoutButton} onPress={handleLogout}>
          <LogOut size={20} color="#EF4444" />
        </TouchableOpacity>
      </View>

      {/* 2. Main Content Screens (Tab Switcher) */}
      <ScrollView contentContainerStyle={styles.scrollContainer}>
        
        {/* TABS 1: CONSOLE HOME */}
        {activeTab === "home" && (
          <View style={styles.tabContent}>
            
            {/* Quick Metrics Grid Summary */}
            <View style={{ flexDirection: "row", gap: 12, paddingHorizontal: 16, marginTop: 10, marginBottom: 6 }}>
              <View style={{ flex: 1, backgroundColor: "#EFF6FF", borderRadius: 20, padding: 14, borderWidth: 1, borderColor: "#BFDBFE" }}>
                <Text style={{ fontSize: 10, color: "#1E40AF", fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.5 }}>Assigned Route</Text>
                <Text style={{ fontSize: 14, fontWeight: "900", color: "#1D4ED8", marginTop: 4 }}>{routeName || "Route #1"}</Text>
              </View>
              <View style={{ flex: 1, backgroundColor: "#ECFDF5", borderRadius: 20, padding: 14, borderWidth: 1, borderColor: "#A7F3D0" }}>
                <Text style={{ fontSize: 10, color: "#065F46", fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.5 }}>Passengers</Text>
                <Text style={{ fontSize: 18, fontWeight: "900", color: "#047857", marginTop: 4 }}>{students.length > 0 ? students.length : totalPassengers}</Text>
              </View>
            </View>

            {/* SOS Button Panel */}
            <View style={styles.section}>
              <View style={styles.sosCard}>
                <View style={styles.sosHeader}>
                  <ShieldAlert size={28} color="#EF4444" />
                  <Text style={styles.sosTitle}>Emergency Broadcast</Text>
                </View>
                <Text style={styles.sosDesc}>
                  Immediately alert all parents, broadcast vehicle coordinates, and trigger sirens in case of mechanical breakdown or accident.
                </Text>
                <TouchableOpacity style={styles.sosBtn} onPress={handleSOS}>
                  <Text style={styles.sosBtnText}>Trigger SOS Siren</Text>
                </TouchableOpacity>
              </View>
            </View>

            {/* Transit Controller Console */}
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Transit Console</Text>
              <View style={styles.consoleCard}>
                <View style={styles.cardHeader}>
                  <Truck size={24} color="#10B981" />
                  <Text style={styles.cardTitle}>Journey Status</Text>
                  <View style={[styles.statusBadge, { backgroundColor: isActive ? "#D1FAE5" : "#F1F5F9" }]}>
                    <Text style={[styles.statusText, { color: isActive ? "#047857" : "#475569" }]}>
                      {isActive ? "ACTIVE" : "OFFLINE"}
                    </Text>
                  </View>
                </View>

                <Text style={styles.consoleDesc}>
                  {isActive 
                    ? "Your live location is actively streaming to the parent map dashboards. Keep Expo open." 
                    : "Ready to start transport routes? Start the trip to begin streaming telemetry."}
                </Text>

                <TouchableOpacity 
                  style={[styles.toggleBtn, isActive ? styles.toggleBtnActive : styles.toggleBtnInactive]}
                  onPress={handleToggleJourney}
                >
                  <Text style={styles.toggleBtnText}>
                    {isActive ? "Complete Journey" : "Start Journey"}
                  </Text>
                </TouchableOpacity>

                {isActive && (
                  <TouchableOpacity 
                    style={[styles.simBtn, isSimulating && styles.simBtnActive]} 
                    onPress={handleToggleSimulator}
                  >
                    <Text style={[styles.simBtnText, isSimulating && styles.simBtnTextActive]}>
                      {isSimulating ? "Stop Simulator Mode" : "Start Simulator Mode"}
                    </Text>
                  </TouchableOpacity>
                )}
              </View>
            </View>

            {/* Announcement Creator (Moved to Home) */}
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Broadcast Announcement</Text>
              <View style={styles.card}>
                <TextInput
                  style={[styles.textInput, { height: 72, textAlignVertical: "top" }]}
                  placeholder="Post announcements, weather changes, or route updates to parents..."
                  placeholderTextColor="#94A3B8"
                  value={announcementMsg}
                  onChangeText={setAnnouncementMsg}
                  multiline
                />
                <TouchableOpacity 
                  style={[styles.actionBtn, isBroadcasting && styles.btnDisabled]}
                  onPress={handleBroadcastAnnouncement}
                  disabled={isBroadcasting}
                >
                  {isBroadcasting ? <ActivityIndicator color="#FFF" /> : <Text style={styles.actionBtnText}>Broadcast Message</Text>}
                </TouchableOpacity>
              </View>
            </View>

            {/* Passenger Checklist Manifest */}
            {isActive && (
              <View style={styles.section}>
                <Text style={styles.sectionTitle}>Passenger Manifest</Text>
                {isLoadingStudents ? (
                  <ActivityIndicator color="#10B981" style={{ marginTop: 12 }} />
                ) : students.length === 0 ? (
                  <View style={styles.card}>
                    <Text style={{ color: "#64748B", textAlign: "center", fontSize: 13, fontWeight: "600" }}>
                      No passengers registered on this route stops.
                    </Text>
                  </View>
                ) : (
                  students.map(item => (
                    <View style={styles.studentCard} key={item.id}>
                      <View style={{ flex: 1 }}>
                        <Text style={styles.studentName}>{item.name}</Text>
                        <Text style={styles.studentMeta}>School: {item.school || "Standard School"}</Text>
                      </View>
                      
                      {item.status === "absent" && (
                        <View style={[styles.badgeContainer, { backgroundColor: "#FEE2E2" }]}>
                          <Text style={{ color: "#EF4444", fontSize: 11, fontWeight: "800" }}>ABSENT</Text>
                        </View>
                      )}

                      {item.status === "awaiting" && (
                        <TouchableOpacity style={[styles.actionBadge, { backgroundColor: "#10B981" }]} onPress={() => handleBoardStudent(item.id)}>
                          <Text style={styles.actionBadgeText}>Board</Text>
                        </TouchableOpacity>
                      )}

                      {item.status === "boarded" && (
                        <TouchableOpacity style={[styles.actionBadge, { backgroundColor: "#F59E0B" }]} onPress={() => handleDropStudent(item.id)}>
                          <Text style={styles.actionBadgeText}>Drop</Text>
                        </TouchableOpacity>
                      )}

                      {item.status === "completed" && (
                        <View style={styles.checkIcon}>
                          <Check size={16} color="#10B981" />
                        </View>
                      )}
                    </View>
                  ))
                )}
              </View>
            )}
          </View>
        )}

        {/* TABS 2: PAYMENTS */}
        {activeTab === "payments" && (
          <View style={styles.tabContent}>
            <View style={styles.controlPanel}>
              <TouchableOpacity 
                style={[styles.generateBtn, isGenerating && styles.btnDisabled]} 
                onPress={handleCalculateDues}
                disabled={isGenerating}
              >
                {isGenerating ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.generateBtnText}>Calculate & Generate Dues</Text>}
              </TouchableOpacity>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Payments List</Text>
              {isLoadingPayments ? (
                <ActivityIndicator color="#10B981" />
              ) : payments.length === 0 ? (
                <View style={styles.card}>
                  <Text style={{ color: "#64748B", textAlign: "center" }}>No student payments records.</Text>
                </View>
              ) : (
                payments.map(item => {
                  const colors = getStatusColor(item.status);
                  return (
                    <View style={styles.paymentCard} key={item.id}>
                      <View style={{ flex: 1 }}>
                        <Text style={styles.studentName}>{item.student_name || `Student #${item.student_id}`}</Text>
                        <Text style={styles.monthLabel}>Month: {item.month} • Dues: LKR {Number(item.amount_due).toFixed(2)}</Text>
                      </View>
                      <View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}>
                        <View style={[styles.badge, { backgroundColor: colors.bg }]}>
                          <Text style={[styles.badgeText, { color: colors.text }]}>{item.status}</Text>
                        </View>
                        {item.status === "receipt_submitted" && (
                          <TouchableOpacity style={styles.verifyBtn} onPress={() => setSelectedPayment(item)}>
                            <FileText size={14} color="#FFF" />
                          </TouchableOpacity>
                        )}
                      </View>
                    </View>
                  );
                })
              )}
            </View>
          </View>
        )}

        {/* TABS 3: JOURNEY NOTIFICATIONS HISTORY */}
        {activeTab === "notifications" && (
          <View style={styles.tabContent}>
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Past Journey Logs</Text>
              {isLoadingHistory ? (
                <ActivityIndicator color="#10B981" />
              ) : journeyHistory.length === 0 ? (
                <View style={styles.card}>
                  <Text style={{ color: "#64748B", textAlign: "center" }}>No journey history recorded.</Text>
                </View>
              ) : (
                journeyHistory.map(item => (
                  <View style={styles.card} key={item.id}>
                    <View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 6 }}>
                      <Text style={{ fontWeight: "800", color: "#0F172A" }}>{item.route_name || "Standard Route"}</Text>
                      <Text style={{ fontSize: 11, color: "#10B981", fontWeight: "800" }}>{item.status}</Text>
                    </View>
                    <Text style={{ fontSize: 12, color: "#64748B" }}>Started: {new Date(item.started_at).toLocaleString()}</Text>
                    {item.completed_at && <Text style={{ fontSize: 12, color: "#64748B" }}>Ended: {new Date(item.completed_at).toLocaleString()}</Text>}
                  </View>
                ))
              )}
            </View>
          </View>
        )}

        {/* TABS 4: PROFILE & NESTED SETTINGS */}
        {activeTab === "profile" && (
          <View style={styles.tabContent}>
            
            {/* Onboarding Wizard Form if not completed */}
            {!onboardingCompleted && (
              <View style={[styles.section, { backgroundColor: "#FFFBEB", padding: 18, borderRadius: 24, borderWidth: 1, borderColor: "#FDE68A" }]}>
                <Text style={{ fontSize: 16, fontWeight: "900", color: "#B45309", marginBottom: 6 }}>Setup Onboarding Profile</Text>
                <Text style={{ fontSize: 12, color: "#D97706", marginBottom: 16 }}>Complete your driver onboarding process to finalize setup.</Text>
                
                <TextInput style={styles.textInput} placeholder="License Number" value={licenseNumber} onChangeText={setLicenseNumber} placeholderTextColor="#94A3B8" />
                <TextInput style={styles.textInput} placeholder="Vehicle Registration No." value={vehicleNumber} onChangeText={setVehicleNumber} placeholderTextColor="#94A3B8" />
                <TextInput style={styles.textInput} placeholder="Vehicle Seats Count" value={vehicleCapacity} onChangeText={setVehicleCapacity} keyboardType="numeric" placeholderTextColor="#94A3B8" />
                <TextInput style={styles.textInput} placeholder="Predefined Route ID/Name" value={routeName} onChangeText={setRouteName} placeholderTextColor="#94A3B8" />
                
                <TouchableOpacity style={styles.actionBtn} onPress={handleOnboardingSubmit} disabled={isOnboardingSubmitting}>
                  {isOnboardingSubmitting ? <ActivityIndicator color="#FFF" /> : <Text style={styles.actionBtnText}>Submit Details</Text>}
                </TouchableOpacity>
              </View>
            )}

            {/* 4A. VIEW PROFILE MODE */}
            {profileSubView === "view" && (
              <>
                <View style={styles.section}>
                  <Text style={styles.sectionTitle}>Driver Identity</Text>
                  <View style={styles.card}>
                    <View style={{ flexDirection: "row", alignItems: "center", gap: 14, marginBottom: 16 }}>
                      <View style={{ height: 48, width: 48, borderRadius: 16, backgroundColor: "#E0F2FE", justifyContent: "center", alignItems: "center" }}>
                        <User size={22} color="#0284C7" />
                      </View>
                      <View>
                        <Text style={{ fontSize: 16, fontWeight: "900", color: "#0F172A" }}>{driverName}</Text>
                        <Text style={{ fontSize: 12, color: "#64748B" }}>Active driver profile</Text>
                      </View>
                    </View>

                    <Text style={{ fontSize: 11, fontWeight: "900", color: "#94A3B8", textTransform: "uppercase", marginTop: 8 }}>Email Address</Text>
                    <Text style={{ fontSize: 13, color: "#334155", fontWeight: "700", marginTop: 2 }}>{driverEmail}</Text>

                    <Text style={{ fontSize: 11, fontWeight: "900", color: "#94A3B8", textTransform: "uppercase", marginTop: 12 }}>Phone Number</Text>
                    <Text style={{ fontSize: 13, color: "#334155", fontWeight: "700", marginTop: 2 }}>{driverPhone || "Not set"}</Text>
                  </View>
                </View>

                {onboardingCompleted && (
                  <>
                    <View style={styles.section}>
                      <Text style={styles.sectionTitle}>Transport Info</Text>
                      <View style={styles.card}>
                        <Text style={{ fontSize: 11, fontWeight: "900", color: "#94A3B8", textTransform: "uppercase" }}>License Number</Text>
                        <Text style={{ fontSize: 13, color: "#334155", fontWeight: "700", marginTop: 2 }}>{licenseNumber}</Text>

                        <Text style={{ fontSize: 11, fontWeight: "900", color: "#94A3B8", textTransform: "uppercase", marginTop: 12 }}>Predefined Route</Text>
                        <Text style={{ fontSize: 13, color: "#334155", fontWeight: "700", marginTop: 2 }}>{routeName || "Route #1"}</Text>
                      </View>
                    </View>

                    <View style={styles.section}>
                      <Text style={styles.sectionTitle}>Vehicle Info</Text>
                      <View style={styles.card}>
                        <Text style={{ fontSize: 11, fontWeight: "900", color: "#94A3B8", textTransform: "uppercase" }}>Registration Number</Text>
                        <Text style={{ fontSize: 13, color: "#334155", fontWeight: "700", marginTop: 2 }}>{vehicleNumber}</Text>

                        <Text style={{ fontSize: 11, fontWeight: "900", color: "#94A3B8", textTransform: "uppercase", marginTop: 12 }}>Vehicle Specifications</Text>
                        <Text style={{ fontSize: 13, color: "#334155", fontWeight: "700", marginTop: 2 }}>{vehicleType.toUpperCase()} ({vehicleCapacity} seats)</Text>
                      </View>
                    </View>
                  </>
                )}

                <View style={{ flexDirection: "row", gap: 12, marginHorizontal: 16, marginTop: 12 }}>
                  <TouchableOpacity style={[styles.actionBtn, { flex: 1, backgroundColor: "#10B981" }]} onPress={() => setProfileSubView("edit")}>
                    <Text style={styles.actionBtnText}>Edit Profile</Text>
                  </TouchableOpacity>
                  <TouchableOpacity style={[styles.actionBtn, { flex: 1, backgroundColor: "#64748B" }]} onPress={() => setProfileSubView("settings")}>
                    <Text style={styles.actionBtnText}>Settings</Text>
                  </TouchableOpacity>
                </View>
              </>
            )}

            {/* 4B. EDIT PROFILE MODE */}
            {profileSubView === "edit" && (
              <View style={styles.section}>
                <Text style={styles.sectionTitle}>Edit Profile details</Text>
                <View style={styles.card}>
                  <Text style={styles.label}>Full Name</Text>
                  <TextInput style={styles.textInput} value={driverName} onChangeText={setDriverName} />

                  <Text style={styles.label}>Email (read-only)</Text>
                  <TextInput style={[styles.textInput, { backgroundColor: "#F1F5F9" }]} value={driverEmail} editable={false} />

                  <Text style={styles.label}>Mobile Number</Text>
                  <TextInput style={styles.textInput} value={driverPhone} onChangeText={setDriverPhone} keyboardType="phone-pad" />

                  <Text style={styles.label}>License Number</Text>
                  <TextInput style={styles.textInput} value={licenseNumber} onChangeText={setLicenseNumber} />

                  <Text style={styles.label}>Vehicle Registration No.</Text>
                  <TextInput style={styles.textInput} value={vehicleNumber} onChangeText={setVehicleNumber} />

                  <Text style={styles.label}>Seats Capacity</Text>
                  <TextInput style={styles.textInput} value={vehicleCapacity} onChangeText={setVehicleCapacity} keyboardType="numeric" />

                  <Text style={styles.label}>Route Name / ID</Text>
                  <TextInput style={styles.textInput} value={routeName} onChangeText={setRouteName} />

                  <TouchableOpacity style={[styles.actionBtn, { marginTop: 16 }]} onPress={handleSaveDriverProfile}>
                    <Text style={styles.actionBtnText}>Save Changes</Text>
                  </TouchableOpacity>
                  <TouchableOpacity style={[styles.actionBtn, { backgroundColor: "#64748B", marginTop: 8 }]} onPress={() => setProfileSubView("view")}>
                    <Text style={styles.actionBtnText}>Cancel</Text>
                  </TouchableOpacity>
                </View>
              </View>
            )}

            {/* 4C. SETTINGS MODE */}
            {profileSubView === "settings" && (
              <>
                {/* NESTED OPTION: Settings Configuration Section */}
                <View style={styles.section}>
                  <Text style={styles.sectionTitle}>Pricing & Billing Settings</Text>
                  <View style={styles.card}>
                    {isLoadingPaymentSettings ? (
                      <ActivityIndicator color="#10B981" />
                    ) : (
                      <>
                        <Text style={styles.label}>Pricing Mode</Text>
                        <View style={styles.roleContainer}>
                          <TouchableOpacity style={[styles.roleBtn, paymentMode === "fixed" && styles.roleBtnActive]} onPress={() => setPaymentMode("fixed")}>
                            <Text style={[styles.roleBtnText, paymentMode === "fixed" && styles.roleBtnTextActive]}>Fixed</Text>
                          </TouchableOpacity>
                          <TouchableOpacity style={[styles.roleBtn, paymentMode === "distance_based" && styles.roleBtnActive]} onPress={() => setPaymentMode("distance_based")}>
                            <Text style={[styles.roleBtnText, paymentMode === "distance_based" && styles.roleBtnTextActive]}>Distance</Text>
                          </TouchableOpacity>
                        </View>

                        <Text style={[styles.label, { marginTop: 12 }]}>Monthly Fixed Rate (LKR)</Text>
                        <TextInput style={styles.textInput} value={fixedAmount} onChangeText={setFixedAmount} keyboardType="numeric" />
                        
                        <Text style={styles.label}>Monthly Due Date Day (1-28)</Text>
                        <TextInput style={styles.textInput} value={dueDateDay} onChangeText={setDueDateDay} keyboardType="numeric" />

                        <Text style={styles.label}>Auto-Generate Prices Day (1-28)</Text>
                        <TextInput 
                          style={styles.textInput} 
                          placeholder="e.g. 1 (optional)"
                          placeholderTextColor="#94A3B8"
                          value={autoGenerateDay} 
                          onChangeText={setAutoGenerateDay} 
                          keyboardType="numeric" 
                        />

                        <TouchableOpacity style={styles.actionBtn} onPress={handleUpdatePaymentSettings}>
                          <Text style={styles.actionBtnText}>Save Pricing settings</Text>
                        </TouchableOpacity>
                      </>
                    )}
                  </View>
                </View>

                {/* Password Profiles Settings */}
                <View style={styles.section}>
                  <Text style={styles.sectionTitle}>Security Settings</Text>
                  <View style={styles.card}>
                    <Text style={styles.label}>Old Password</Text>
                    <TextInput style={styles.textInput} secureTextEntry value={oldPassword} onChangeText={setOldPassword} placeholder="••••••••" placeholderTextColor="#94A3B8" />

                    <Text style={styles.label}>New Password</Text>
                    <TextInput style={styles.textInput} secureTextEntry value={newPassword} onChangeText={setNewPassword} placeholder="••••••••" placeholderTextColor="#94A3B8" />

                    <TouchableOpacity style={styles.actionBtn} onPress={handleUpdatePassword} disabled={isSubmittingPassword}>
                      {isSubmittingPassword ? <ActivityIndicator color="#FFF" /> : <Text style={styles.actionBtnText}>Update Password</Text>}
                    </TouchableOpacity>
                  </View>
                </View>

                {/* Appearance Settings */}
                <View style={styles.section}>
                  <Text style={styles.sectionTitle}>Appearance & Theme</Text>
                  <View style={[styles.card, { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }]}>
                    <Text style={{ fontSize: 13, fontWeight: "700", color: "#334155" }}>Dark Mode Options</Text>
                    <Switch
                      value={isDarkMode}
                      onValueChange={handleToggleDarkMode}
                      trackColor={{ false: "#E2E8F0", true: "#A7F3D0" }}
                      thumbColor={isDarkMode ? "#10B981" : "#94A3B8"}
                    />
                  </View>
                </View>

                {/* Notification Settings */}
                <View style={styles.section}>
                  <Text style={styles.sectionTitle}>Notifications Config</Text>
                  <View style={[styles.card, { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }]}>
                    <Text style={{ fontSize: 13, fontWeight: "700", color: "#334155" }}>Enable Push Alerts</Text>
                    <Switch
                      value={isNotificationsEnabled}
                      onValueChange={setIsNotificationsEnabled}
                      trackColor={{ false: "#E2E8F0", true: "#A7F3D0" }}
                      thumbColor={isNotificationsEnabled ? "#10B981" : "#94A3B8"}
                    />
                  </View>
                </View>

                {/* Tracking Settings */}
                <View style={styles.section}>
                  <Text style={styles.sectionTitle}>Live Tracking Frequencies</Text>
                  <View style={styles.card}>
                    <View style={{ flexDirection: "row", gap: 8 }}>
                      {["low", "medium", "high"].map((freq) => (
                        <TouchableOpacity
                          key={freq}
                          style={[styles.roleBtn, { flex: 1 }, trackingFrequency === freq && styles.roleBtnActive]}
                          onPress={() => setTrackingFrequency(freq)}
                        >
                          <Text style={[styles.roleBtnText, trackingFrequency === freq && styles.roleBtnTextActive, { textTransform: "capitalize" }]}>
                            {freq}
                          </Text>
                        </TouchableOpacity>
                      ))}
                    </View>
                  </View>
                </View>

                {/* Reset Settings */}
                <View style={styles.section}>
                  <Text style={styles.sectionTitle}>System Reset</Text>
                  <View style={[styles.card, { flexDirection: "row", gap: 12 }]}>
                    <TouchableOpacity style={[styles.actionBtn, { flex: 1, backgroundColor: "#E2E8F0" }]} onPress={() => Alert.alert("Cache Cleared", "Temporary logs cache cleared successfully.")}>
                      <Text style={[styles.actionBtnText, { color: "#475569" }]}>Clear Cache</Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={[styles.actionBtn, { flex: 1, backgroundColor: "#EF4444" }]} onPress={() => Alert.alert("Reset Completed", "All onboarding flows have been reset.")}>
                      <Text style={styles.actionBtnText}>Reset Apps</Text>
                    </TouchableOpacity>
                  </View>
                </View>

                {/* Profile Account Deletion (Basic Section Settings) */}
                <View style={styles.section}>
                  <Text style={styles.sectionTitle}>Delete Profile Account</Text>
                  <View style={styles.card}>
                    <Text style={{ fontSize: 11, color: "#EF4444", fontWeight: "700", marginBottom: 12 }}>
                      Permanently wipe all records, passenger manifest references, and billing details from our system.
                    </Text>
                    <TouchableOpacity style={[styles.actionBtn, { backgroundColor: "#EF4444" }]} onPress={handleDeleteAccount}>
                      <Text style={styles.actionBtnText}>Delete Account & Data</Text>
                    </TouchableOpacity>
                  </View>
                </View>

                <TouchableOpacity style={[styles.actionBtn, { backgroundColor: "#64748B", marginHorizontal: 16, marginBottom: 20 }]} onPress={() => setProfileSubView("view")}>
                  <Text style={styles.actionBtnText}>Back to Profile</Text>
                </TouchableOpacity>
              </>
            )}
          </View>
        )}
      </ScrollView>

      {/* 3. Bottom Navigation Tab Bar (Stick Footer Layout) */}
      <View style={[styles.tabBar, { backgroundColor: themeColors.headerBg, borderColor: themeColors.border }]}>
        <TouchableOpacity style={[styles.tabItem, activeTab === "home" && styles.tabItemActive]} onPress={() => setActiveTab("home")}>
          <Truck size={20} color={activeTab === "home" ? "#10B981" : themeColors.textSecondary} />
          <Text style={[styles.tabItemText, { color: themeColors.textSecondary }, activeTab === "home" && styles.tabItemTextActive]}>Home</Text>
        </TouchableOpacity>

        <TouchableOpacity style={[styles.tabItem, activeTab === "payments" && styles.tabItemActive]} onPress={() => setActiveTab("payments")}>
          <CreditCard size={20} color={activeTab === "payments" ? "#10B981" : themeColors.textSecondary} />
          <Text style={[styles.tabItemText, { color: themeColors.textSecondary }, activeTab === "payments" && styles.tabItemTextActive]}>Payments</Text>
        </TouchableOpacity>

        <TouchableOpacity style={[styles.tabItem, activeTab === "notifications" && styles.tabItemActive]} onPress={() => setActiveTab("notifications")}>
          <Bell size={20} color={activeTab === "notifications" ? "#10B981" : themeColors.textSecondary} />
          <Text style={[styles.tabItemText, { color: themeColors.textSecondary }, activeTab === "notifications" && styles.tabItemTextActive]}>Notifications</Text>
        </TouchableOpacity>

        <TouchableOpacity style={[styles.tabItem, activeTab === "profile" && styles.tabItemActive]} onPress={() => setActiveTab("profile")}>
          <User size={20} color={activeTab === "profile" ? "#10B981" : themeColors.textSecondary} />
          <Text style={[styles.tabItemText, { color: themeColors.textSecondary }, activeTab === "profile" && styles.tabItemTextActive]}>Profile</Text>
        </TouchableOpacity>
      </View>

      {/* Review Receipt Modal */}
      <Modal
        visible={selectedPayment !== null}
        animationType="slide"
        transparent={true}
        onRequestClose={() => setSelectedPayment(null)}
      >
        <View style={styles.modalOverlay}>
          <View style={styles.modalContent}>
            <Text style={styles.modalTitle}>Review Payment</Text>
            {selectedPayment && (
              <>
                <Text style={styles.modalDesc}>
                  Verifying payment from student:{"\n"}
                  <Text style={{ fontWeight: "800" }}>{selectedPayment.student_name}</Text>{"\n"}
                  Amount: LKR {Number(selectedPayment.amount_due).toFixed(2)}
                </Text>
                <Text style={styles.modalMeta}>Reference Code: {selectedPayment.receipt_ref || "N/A"}</Text>

                <TextInput
                  style={styles.textInput}
                  placeholder="Rejection remarks (required only if rejecting)"
                  value={rejectReason}
                  onChangeText={setRejectReason}
                  placeholderTextColor="#94A3B8"
                />

                <View style={styles.modalActions}>
                  <TouchableOpacity style={[styles.modalBtn, styles.declineBtn]} onPress={() => handleVerifyReceipt("rejected")} disabled={isSubmittingVerification}>
                    <X size={18} color="#FFFFFF" style={{ marginRight: 6 }} />
                    <Text style={styles.btnText}>Reject</Text>
                  </TouchableOpacity>

                  <TouchableOpacity style={[styles.modalBtn, styles.approveBtn]} onPress={() => handleVerifyReceipt("paid")} disabled={isSubmittingVerification}>
                    <Check size={18} color="#FFFFFF" style={{ marginRight: 6 }} />
                    <Text style={styles.btnText}>Approve</Text>
                  </TouchableOpacity>
                </View>

                <TouchableOpacity style={styles.closeBtn} onPress={() => setSelectedPayment(null)} disabled={isSubmittingVerification}>
                  <Text style={styles.closeBtnText}>Dismiss</Text>
                </TouchableOpacity>
              </>
            )}
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
}

const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  scrollContainer: {
    padding: 24,
    paddingBottom: 100,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 18,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderColor: "#E2E8F0",
  },
  welcome: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748B",
  },
  name: {
    fontSize: 22,
    fontWeight: "900",
    color: "#0F172A",
    letterSpacing: -0.5,
    marginTop: 2,
  },
  logoutButton: {
    height: 44,
    width: 44,
    borderRadius: 12,
    backgroundColor: "#FEE2E2",
    justifyContent: "center",
    alignItems: "center",
  },
  tabContent: {
    gap: 20,
  },
  section: {
    gap: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#0F172A",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
  },
  sosCard: {
    backgroundColor: "#FEF2F2",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  sosHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  sosTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#991B1B",
  },
  sosDesc: {
    fontSize: 13,
    color: "#7F1D1D",
    lineHeight: 20,
    marginBottom: 16,
  },
  sosBtn: {
    height: 48,
    backgroundColor: "#EF4444",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  sosBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  consoleCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#0F172A",
    flex: 1,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  statusText: {
    fontSize: 10,
    fontWeight: "900",
  },
  consoleDesc: {
    fontSize: 13,
    color: "#64748B",
    lineHeight: 20,
    marginBottom: 18,
  },
  toggleBtn: {
    height: 52,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  toggleBtnInactive: {
    backgroundColor: "#10B981",
  },
  toggleBtnActive: {
    backgroundColor: "#0F172A",
  },
  toggleBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
  simBtn: {
    height: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
    backgroundColor: "#F8FAFC",
  },
  simBtnActive: {
    backgroundColor: "#EFF6FF",
    borderColor: "#3B82F6",
  },
  simBtnText: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: "700",
  },
  simBtnTextActive: {
    color: "#2563EB",
  },
  studentCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  studentName: {
    fontSize: 15,
    fontWeight: "800",
    color: "#0F172A",
  },
  studentMeta: {
    fontSize: 12,
    color: "#94A3B8",
    marginTop: 2,
  },
  badgeContainer: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  actionBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  actionBadgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
  },
  checkIcon: {
    height: 28,
    width: 28,
    borderRadius: 14,
    backgroundColor: "#D1FAE5",
    justifyContent: "center",
    alignItems: "center",
  },
  textInput: {
    height: 52,
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 16,
    fontSize: 14,
    color: "#0F172A",
    marginBottom: 16,
  },
  actionBtn: {
    height: 52,
    backgroundColor: "#10B981",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  actionBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  controlPanel: {
    marginBottom: 8,
  },
  generateBtn: {
    height: 52,
    backgroundColor: "#0F172A",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  generateBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
  paymentCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  monthLabel: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 4,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  verifyBtn: {
    height: 32,
    width: 32,
    borderRadius: 8,
    backgroundColor: "#10B981",
    justifyContent: "center",
    alignItems: "center",
  },
  label: {
    fontSize: 12,
    fontWeight: "800",
    color: "#64748B",
    textTransform: "uppercase",
    marginBottom: 8,
  },
  roleContainer: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  roleBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    justifyContent: "center",
    alignItems: "center",
  },
  roleBtnActive: {
    backgroundColor: "#EFF6FF",
    borderColor: "#3B82F6",
  },
  roleBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#64748B",
  },
  roleBtnTextActive: {
    color: "#2563EB",
  },
  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 72,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderColor: "#E2E8F0",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingBottom: 8,
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  tabItemActive: {},
  tabItemText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#64748B",
    marginTop: 4,
  },
  tabItemTextActive: {
    color: "#10B981",
  },
  btnDisabled: {
    opacity: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 28,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#0F172A",
    marginBottom: 12,
  },
  modalDesc: {
    fontSize: 13,
    color: "#334155",
    lineHeight: 20,
    marginBottom: 8,
  },
  modalMeta: {
    fontSize: 11,
    fontWeight: "800",
    color: "#10B981",
    marginBottom: 16,
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  modalBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  approveBtn: {
    backgroundColor: "#10B981",
  },
  declineBtn: {
    backgroundColor: "#EF4444",
  },
  btnText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 13,
  },
  closeBtn: {
    alignItems: "center",
    paddingVertical: 8,
  },
  closeBtnText: {
    color: "#64748B",
    fontWeight: "700",
    fontSize: 13,
  }
});
